name: Rust CI

on:
  push:
   
jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'
  build:
    runs-on: ubuntu-latest
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    needs: 
      - get-version
    #runs-on: ${{matrix.os}}
    #strategy:
     # matrix:
      #  os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set-up Rust
      uses: actions-rs/toolchain@v1.0.6
      with:    
        toolchain: stable
        target: wasm32-unknown-unknown
    
        
    - name: dependencies
      run: |
        cargo install trunk wasm-bindgen-cli

    - name: build 
      run: trunk build --release

    - name: upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with: 
           name: rust
           path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [get-version, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: rust
          path: dist
          
        env:
          GH-TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
    
  
